### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by ruuti** [0xFFse/sms-burner#14]
Add `meta` tags to both `/` and `/about` -pages. Suggestion:

- `<meta name="description" content="" />`
- `<meta property="og:description" content="" /> `
- `<meta property="og:title" content="" />`
- `<meta property="og:type" content="website" />`
- `<meta name="twitter:card" content="summary">`
- `<meta name="twitter:site" content="" />`
- `<meta name="twitter:title" content="" />`
- `<meta name="twitter:description" content="" />`
- `<meta name="twitter:image" content="" /> `
- `<meta property="og:image" content="" />`
- `<meta property="og:description" content="" />`
- `<meta property="og:site_name" content="" />`

**Comment by ruuti** [comment]
@m0xffse could you take a look at some of them? Maybe:

- `(*:)description`
- `(*:)title`
- `twitter:site`

Maybe something has to happen as well on Twitter to verify the domain?

**Comment by m0xffse** [comment]
Fixed with #16
