### ISSUE TITLE
Copy-to-clipboard icon on phone numbers

### ISSUE THREAD

**Issue by m0xffse** [0xFFse/sms-burner#22]
Would simplify when copying the numbers to registration forms.

**Comment by m0xffse** [comment]
Doesn't really make sense to have a tel: link on the number either, just annoying right now as it makes the numbers harder to copy.

**Comment by m0xffse** [comment]
@ruuti Something you can look at?

**Comment by ruuti** [comment]
Seems like a reasonable improvement. I could swear iOS used to have a copy option when you clicked tel -link. Or is it on Android?

Anyway, I'll take a look at this.
